import React from 'react'
import Head from 'next/head'
import Index from '../component/LearningCenter/Index'

const learningcenter = () => {
  return (
    <div>
        <Head>
            <title>Gratis digital world</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
            <main>
                <Index/>
            </main>
    </div>
  )
}

export default learningcenter