import React from 'react'
import Head from 'next/head'
import Index from '../component/LearningCenter/Index'

const learningcenter = () => {
  return (
    <div>
        <Head>
            <title>Gratis digital world</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,300,0,200" />
            <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,300,0,200" />

        </Head>
            <main>
                <Index/>
            </main>
    </div>
  )
}

export default learningcenter